# Generated by Django 6.0.6 on 2026-08-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserInformation",
            fields=[
                ("UserId", models.AutoField(primary_key=True, serialize=False)),
                ("UserRole", models.CharField(default="Customer", max_length=12)),
                ("UserName", models.CharField(max_length=15)),
                ("UserEmailAddress", models.EmailField(max_length=254)),
                ("UserPassword", models.CharField(max_length=20)),
                ("UserContact", models.CharField(max_length=13)),
            ],
        ),
    ]
