# Generated by Django 6.0.6 on 2026-08-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinformation",
            name="UserRole",
            field=models.CharField(
                choices=[
                    ("Customer", "Customer"),
                    ("Chef", "Chef"),
                    ("Manager", "Manager"),
                ],
                max_length=20,
            ),
        ),
    ]
