# Generated by Django 6.0.6 on 2026-08-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0003_alter_userinformation_userrole"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinformation",
            name="UserName",
            field=models.CharField(max_length=30),
        ),
    ]
