# Generated by Django 6.0.6 on 2026-08-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HotelTables",
            fields=[
                ("TableId", models.AutoField(primary_key=True, serialize=False)),
                ("TableName", models.CharField(max_length=20, unique=True)),
                (
                    "TableZone",
                    models.CharField(
                        choices=[
                            ("Indoor", "Indoor"),
                            ("Garden", "Garden"),
                            ("Rooftop", "Rooftop"),
                            ("VIP", "VIP"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "TableZoneLabel",
                    models.CharField(
                        choices=[
                            ("Main Hall (AC)", "Main Hall (AC)"),
                            ("Garden Patio", "Garden Patio"),
                            ("VIP Lounge", "VIP Lounge"),
                            ("Rooftop Terrace", "Rooftop Terrace"),
                        ],
                        max_length=20,
                    ),
                ),
                ("TableSeatSize", models.IntegerField(max_length=10)),
                (
                    "TablesStatus",
                    models.CharField(
                        choices=[
                            ("Available", "Available"),
                            ("Occupied", "Occupied"),
                            ("Reserved", "Reserved"),
                        ],
                        max_length=20,
                    ),
                ),
                ("TableFeatures", models.TextField(max_length=30)),
            ],
        ),
    ]
