# Generated by Django 6.0.6 on 2026-08-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tables", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hoteltables",
            name="TableSeatSize",
            field=models.CharField(
                choices=[
                    ("1", "1"),
                    ("2", "2"),
                    ("3", "3"),
                    ("4", "4"),
                    ("5", "5"),
                    ("6", "6"),
                    ("7", "7"),
                    ("8", "8"),
                    ("9", "9"),
                    ("10", "10"),
                ],
                max_length=10,
            ),
        ),
    ]
