# Generated by Django 6.0.6 on 2026-08-06 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0004_alter_userinformation_username"),
        ("Tables", "0002_alter_hoteltables_tableseatsize"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeatBooking",
            fields=[
                ("SeatBookingId", models.AutoField(primary_key=True, serialize=False)),
                ("BookingDateTime", models.DateTimeField(auto_now_add=True)),
                (
                    "SeatBookingStatus",
                    models.CharField(
                        choices=[
                            ("Available", "Available"),
                            ("Reserved", "Reserved"),
                            ("NotAvailable", "NotAvailable"),
                            ("Canceled", "Canceled"),
                            ("Completed", "Completed"),
                        ]
                    ),
                ),
                (
                    "Table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Tables.hoteltables",
                    ),
                ),
                (
                    "User",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Account.userinformation",
                    ),
                ),
            ],
        ),
    ]
