# Generated by Django 6.0.6 on 2026-08-07 15:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tables", "0003_seatbooking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seatbooking",
            name="BookingDateTime",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
