# Generated by Django 6.0.6 on 2026-08-08 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Account", "0004_alter_userinformation_username"),
        ("Tables", "0004_alter_seatbooking_bookingdatetime"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodOrder",
            fields=[
                ("OrderId", models.AutoField(primary_key=True, serialize=False)),
                ("OrderDateTime", models.DateTimeField(auto_now_add=True)),
                (
                    "OrderStatus",
                    models.CharField(
                        choices=[
                            ("Received", "Received"),
                            ("Accepted", "Accepted"),
                            ("Preparing", "Preparing"),
                            ("Cooking", "Cooking"),
                            ("Ready", "Ready"),
                            ("Served", "Served"),
                            ("Completed", "Completed"),
                            ("Canceled", "Canceled"),
                        ],
                        default="Received",
                        max_length=20,
                    ),
                ),
                ("SpecialInstructions", models.TextField(blank=True, null=True)),
                (
                    "Table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="Tables.hoteltables",
                    ),
                ),
                (
                    "User",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="Account.userinformation",
                    ),
                ),
            ],
        ),
    ]
