# Generated by Django 6.0.6 on 2026-09-07 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Kitchen", "0001_initial"),
        ("menu", "0003_alter_foodmenu_fooditemtype"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodorder",
            name="DiscountAmount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="foodorder",
            name="GstAmount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="foodorder",
            name="PaymentMethod",
            field=models.CharField(
                choices=[
                    ("UPI", "UPI"),
                    ("Card", "Card"),
                    ("Cash", "Cash"),
                    ("NetBanking", "NetBanking"),
                ],
                default="UPI",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="foodorder",
            name="PaymentStatus",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Paid", "Paid"),
                    ("Refunded", "Refunded"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="foodorder",
            name="SubtotalAmount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="foodorder",
            name="TotalAmount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name="FoodOrderItem",
            fields=[
                ("OrderItemId", models.AutoField(primary_key=True, serialize=False)),
                ("Quantity", models.IntegerField(default=1)),
                ("ItemPrice", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "SpecialInstructions",
                    models.TextField(blank=True, default="", null=True),
                ),
                (
                    "FoodItem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="menu.foodmenu",
                    ),
                ),
                (
                    "Order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="Kitchen.foodorder",
                    ),
                ),
            ],
        ),
    ]
