# Generated by Django 6.0.6 on 2026-08-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FoodCategory",
            fields=[
                ("FoodCategoryId", models.AutoField(primary_key=True, serialize=False)),
                (
                    "FoodCategoryName",
                    models.CharField(
                        choices=[
                            ("Starters", "Starters"),
                            ("Pure-Veg", "Veg-Veg"),
                            ("Non-Veg", "Non-Veg"),
                            ("Drinks & Shakes", "Drinks & Shakes"),
                        ],
                        max_length=20,
                    ),
                ),
                ("FoodCategoryIcon", models.CharField(max_length=20)),
                ("FoodCategoryDescription", models.TextField(max_length=30)),
            ],
        ),
    ]
