# Generated by Django 6.0.6 on 2026-08-07 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodMenu",
            fields=[
                ("FoodItemId", models.AutoField(primary_key=True, serialize=False)),
                ("FoodItemName", models.CharField(max_length=50)),
                (
                    "FoodItemType",
                    models.CharField(
                        choices=[("Veg", "Veg"), ("Non-Veg", "Non-Veg")], max_length=40
                    ),
                ),
                ("FoodItemPrice", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "FoodItemRating",
                    models.DecimalField(decimal_places=1, default=0, max_digits=2),
                ),
                ("FoodPreparationTime", models.CharField(max_length=20)),
                ("FoodItemImage", models.URLField(max_length=650)),
                ("FoodItemDescription", models.TextField(max_length=150)),
                ("FoodItemIngredients", models.TextField(max_length=150)),
                ("FoodItemAvailable", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="menu.foodcategory",
                    ),
                ),
            ],
        ),
    ]
