# Generated by Django 6.0.6 on 2026-08-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_foodmenu"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodmenu",
            name="FoodItemType",
            field=models.CharField(
                choices=[("veg", "veg"), ("Non-Veg", "Non-Veg")], max_length=40
            ),
        ),
    ]
